stages:
  - flake8
  - pylint
  - mypy
  - pytest

.default_python_job:
  image: python:3.13
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$HOME/.local/bin:$PATH"
    - poetry config virtualenvs.create false
    - poetry install
  only:
    - merge_requests
    - main

flake8:
  stage: flake8
  extends: .default_python_job
  script:
    - poetry run flake8 .

mypy:
  stage: mypy
  extends: .default_python_job
  script:
    - poetry run mypy .

pylint:
  stage: pylint
  extends: .default_python_job
  script:
    - cp .env.example .env
    - poetry run pylint .

pytest:
  stage: pytest
  extends: .default_python_job
  script:
    - cp .env.example .env
    - poetry run pytest --cov=src --cov-report=term-missing
